### ISSUE TITLE
reference of the monocular estimator 

### ISSUE THREAD

**Issue by Van5SE** [goldoak/DMSR#5]
Hi there, I found the reference [26] of monocular estimator in your paper was wrong. Could you please tell me which article you referred?
Thank you!

**Comment by goldoak** [comment]
Hi, the reference is correct. It is a book written by David Marr and was originally published in 1982 by W. H. Freeman and Company. If you want to read this book, please search on the internet with the title "Vision: A Computational Investigation into the Human Representation and Processing of Visual Information".

**Comment by Van5SE** [comment]
Thank you for your reply!
